/* sonelle tab names: a large pool of women's names so each terminal tab reads like a person
   (Megan, Sakura, Sidney...) instead of "sonelle 1 / sonelle 2". Pure ASCII (accents folded:
   Zoe not Zoe-with-diaeresis, Chloe not Chloe-with-acute) so it stays encoding-safe. app.js
   picks one at random per tab, preferring one not already on an open tab. Deliberately diverse
   across cultures; extend freely - app.js degrades to "sonelle" if this list is ever empty. */
(function () {
  "use strict";
  window.SONELLE_NAMES = [
    "Aaliyah", "Abigail", "Ada", "Adaeze", "Adriana", "Agnes", "Aiko", "Ainsley", "Aisha", "Akira",
    "Alana", "Alba", "Alejandra", "Alena", "Alessia", "Alexa", "Alice", "Alina", "Alison", "Allegra",
    "Amara", "Amber", "Amelia", "Amina", "Amira", "Anaya", "Anastasia", "Andrea", "Anika", "Anita",
    "Anja", "Anna", "Annabel", "Anneliese", "Antonia", "Anya", "Aoife", "April", "Arden", "Aria",
    "Ariana", "Arielle", "Asha", "Ashanti", "Ashley", "Astrid", "Aurora", "Ava", "Avery", "Ayana",
    "Ayesha", "Azra",
    "Bailey", "Beatrice", "Bella", "Bernadette", "Beth", "Bianca", "Blair", "Bonnie", "Briana",
    "Bridget", "Brielle", "Brooke", "Brynn",
    "Cadence", "Caitlin", "Calliope", "Camila", "Camille", "Cara", "Carla", "Carmen", "Caroline",
    "Cassandra", "Catalina", "Catherine", "Cecilia", "Celeste", "Celine", "Chandra", "Charlotte",
    "Chelsea", "Cheryl", "Chiamaka", "Chiara", "Chloe", "Clara", "Claudia", "Clementine", "Colette",
    "Cora", "Cordelia", "Cynthia",
    "Dahlia", "Daisy", "Dalia", "Damaris", "Dana", "Daniela", "Daphne", "Darya", "Davina", "Dawn",
    "Delphine", "Demi", "Denise", "Diana", "Dina", "Dione", "Dolores", "Dominique", "Dora", "Dorothy",
    "Dua",
    "Ebony", "Eden", "Edith", "Effie", "Eileen", "Elaine", "Eleanor", "Elena", "Eliana", "Elif",
    "Elisa", "Eliza", "Ella", "Elodie", "Eloise", "Elsa", "Elspeth", "Emelia", "Emiko", "Emily",
    "Emma", "Emmanuelle", "Enid", "Esme", "Esperanza", "Estelle", "Esther", "Etta", "Eunice", "Eva",
    "Evangeline", "Evelyn", "Evie",
    "Fadia", "Faith", "Farida", "Fatima", "Fay", "Felicity", "Fern", "Fiona", "Flora", "Florence",
    "Frances", "Francesca", "Freya", "Frida",
    "Gabriela", "Gail", "Galina", "Gemma", "Genevieve", "Georgia", "Gianna", "Gigi", "Gillian",
    "Gina", "Giselle", "Gloria", "Grace", "Greta", "Gwen", "Gwendolyn",
    "Hana", "Hannah", "Harlow", "Harmony", "Harper", "Hazel", "Heather", "Hedda", "Heidi", "Helen",
    "Helena", "Henrietta", "Hester", "Hilda", "Holly", "Hope", "Hyacinth",
    "Ida", "Iman", "Imani", "Imogen", "India", "Indira", "Ines", "Ingrid", "Iona", "Irene", "Iris",
    "Isabel", "Isabella", "Isadora", "Isla", "Ivy", "Iyla",
    "Jacinda", "Jade", "Jamila", "Jana", "Jane", "Janelle", "Janet", "Jasmine", "Jaya", "Jemima",
    "Jenna", "Jennifer", "Jessamine", "Jessica", "Jewel", "Jia", "Jillian", "Joan", "Joanna",
    "Jocelyn", "Johanna", "Jolene", "Jordan", "Josephine", "Joy", "Juana", "Judith", "Julia",
    "Juliet", "June", "Juniper", "Juno", "Justine",
    "Kaia", "Kala", "Kalinda", "Kamala", "Kara", "Karen", "Karina", "Kat", "Kate", "Katherine",
    "Kavya", "Kayla", "Keira", "Kelly", "Kenya", "Keziah", "Khadija", "Kiara", "Kira", "Kiri",
    "Kirsten", "Klara", "Kora", "Kyla",
    "Lacey", "Laila", "Lana", "Lara", "Larissa", "Laura", "Laurel", "Lavinia", "Leah", "Leila",
    "Lena", "Leona", "Leonie", "Lia", "Liana", "Libby", "Lila", "Lilian", "Lily", "Lina", "Linda",
    "Linnea", "Liora", "Lisa", "Liv", "Lois", "Lola", "Lorelei", "Lorena", "Lottie", "Louisa",
    "Lucia", "Lucille", "Lucinda", "Lucy", "Luna", "Lydia", "Lyra",
    "Mabel", "Madeleine", "Madhuri", "Madison", "Mae", "Magdalena", "Maggie", "Maia", "Maja",
    "Malia", "Mara", "Marceline", "Margaret", "Margot", "Maria", "Mariam", "Marie", "Marina",
    "Marisol", "Marlene", "Marnie", "Martha", "Mary", "Matilda", "Maud", "Maureen", "Mavis",
    "Maxine", "Maya", "Mayra", "Meera", "Megan", "Mei", "Melanie", "Melissa", "Mercedes",
    "Meredith", "Mia", "Mila", "Mina", "Minka", "Mira", "Mirabel", "Miranda", "Miriam", "Misaki",
    "Molly", "Mona", "Monica", "Morgan", "Moriah", "Muriel", "Myra",
    "Nadia", "Nadine", "Naima", "Nala", "Nancy", "Naomi", "Natalia", "Natalie", "Natasha", "Nayeli",
    "Nell", "Neve", "Nia", "Niamh", "Nicole", "Nika", "Nina", "Noa", "Noelle", "Noor", "Nora",
    "Norah", "Nova", "Nyala",
    "Octavia", "Odette", "Ofelia", "Oksana", "Olive", "Olivia", "Olwen", "Oona", "Opal", "Ophelia",
    "Oriana", "Orla",
    "Padma", "Paige", "Paloma", "Pamela", "Paola", "Patricia", "Paula", "Pearl", "Penelope", "Penny",
    "Perpetua", "Petra", "Phoebe", "Pia", "Pilar", "Piper", "Polly", "Poppy", "Portia", "Priya",
    "Prudence",
    "Qiana", "Quinn",
    "Rabia", "Rachel", "Radha", "Rafaela", "Raina", "Ramona", "Rania", "Raquel", "Raven", "Reagan",
    "Rebecca", "Regina", "Reina", "Renata", "Rhea", "Rhiannon", "Ria", "Rina", "Rita", "River",
    "Robin", "Rohini", "Romy", "Rosa", "Rosalind", "Rose", "Rosemary", "Rowan", "Roxana", "Ruby",
    "Ruth",
    "Saanvi", "Sabrina", "Sade", "Sadie", "Safiya", "Sage", "Sakura", "Salma", "Samara", "Samira",
    "Sana", "Sandra", "Saoirse", "Sara", "Sarah", "Sasha", "Saskia", "Savannah", "Scarlett",
    "Selena", "Selma", "Serena", "Shakira", "Shanti", "Sharon", "Sheila", "Shreya", "Sidney",
    "Sienna", "Sigrid", "Simone", "Sinead", "Siobhan", "Sky", "Sofia", "Solveig", "Sonia", "Sophia",
    "Sophie", "Stella", "Stephanie", "Sumi", "Susanna", "Suzanne", "Sybil", "Sydney", "Sylvia",
    "Tabitha", "Talia", "Tamar", "Tamara", "Tanvi", "Tanya", "Tara", "Tatiana", "Tegan", "Teresa",
    "Tess", "Thalia", "Thea", "Theodora", "Therese", "Tia", "Tiana", "Tilly", "Tina", "Tomoko",
    "Tora", "Trinity", "Trudy",
    "Uma", "Ursula",
    "Valentina", "Valerie", "Vanessa", "Vera", "Verena", "Veronica", "Vesna", "Victoria", "Vida",
    "Viola", "Violet", "Virginia", "Vivian", "Vivienne",
    "Wanda", "Wendy", "Wilhelmina", "Willa", "Willow", "Winifred", "Winona", "Wren",
    "Ximena", "Xochitl",
    "Yael", "Yara", "Yasmin", "Yelena", "Yoko", "Yolanda", "Yuki", "Yumi", "Yvonne",
    "Zadie", "Zahra", "Zaria", "Zelda", "Zhanna", "Zinnia", "Zoe", "Zofia", "Zola", "Zora", "Zsofia",
    "Zuri"
  ];
})();
